spring.application.name=basic-rate-limiter

server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

basic.rate.limiter.config.admin-key=${ADMIN_KEY}
app.jwt.secret=${APP_JWT_SECRET}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.repositories.enabled=false

admin.api-key=${ADMIN_API_KEY}

management.server.port=${MANAGEMENT_SERVER_PORT}
management.endpoints.web.exposure.include=${ACTUATOR_WEB_EXPOSURE_INCLUDE}
management.metrics.tags.application=${spring.application.name}